language: cpp

compiler:
  - gcc

env:
  # Note: we cannot give -Werror, as this confuses ./configure
  - CFLAGS="-Wall -Wextra -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Wuninitialized"

before_install:
  - set

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make
  - export VERBOSE=1
  - make check
  # most tests currently fail under "make distcheck", but we enable those
  # that work (see also https://github.com/rsyslog/libfastjson/issues/43 )
  - export MAKEOPTS=-j1
  - make distcheck TESTS="chk_version"
