language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
      - tree

env:
  # Note: we cannot give -Werror, as this confuses ./configure
  - CFLAGS="-Wall -Wextra -Wformat-security -Wshadow -Wcast-align -Wpointer-arith -Wmissing-format-attribute -Wuninitialized"

before_install:
  - set

install:
  - sh autogen.sh

before_script:
  - ./configure

script:
  - make 1>/dev/null 2>&1
  - export VERBOSE=1
  - make check 1>/dev/null 2>&1
  # most tests currently fail under "make distcheck", but we enable those
  # that work (see also https://github.com/rsyslog/libfastjson/issues/43 )
  - export MAKEOPTS=-j1
  - if ! make distcheck TESTS="chk_version"; then  tree -fa ../ && cat Makefile ; fi
